mysql:
  host: "localhost"
  port: 3306
  database: "lotus"
  username: "root"
  password: ""

#This is for hcf servers if they run on a mysql database. You can then get deathbans or any other information you want. There is no official manager on the plugin to use this you must make it yourself.
server:
  host: "localhost"
  port: 3306
  database: "fall"
  username: "root"
  password: ""

items:
  server-selector:
    material: "COMPASS"
    name: "SERVER_SELECTOR"
    display-name: "&7* &6Server-Selector"
    slot: 0
    lore:
      - ""
      - "&7&oNavigate through the network"
      - ""
  visibility:
    material-false: "INK_SACK"
    material-false-data: "8"
    material-true: "INK_SACK"
    material-true-data: "10"
    name: "Visibility"
    display-name: "&7* &6Visibility"
    slot: 2
    lore:
      - ""
      - "&7&oToggle player visibility"
      - ""
  settings:
    material: "ITEM_FRAME"
    name: "ITEM_FRAME"
    display-name: "&7* &6Settings"
    slot: 4
    lore:
      - ""
      - "&7&oChange your profile settings"
      - ""
  cosmetics:
    material: "CHEST"
    name: "CHEST"
    display-name: "&7* &6Cosmetics"
    slot: 6
    lore:
      - ""
      - "&7&oChange your profile settings"
      - ""
  ender-butt:
    material: "ENDER_PEARL"
    name: "ENDER_PEARL"
    display-name: "&7* &6Ender-Butt"
    slot: 8
    lore:
      - ""
      - "&7&oGet some cool things!"
      - ""

scoreboard:
  title: "&6Your Server"
  lines:
    queue:
      - "&7&m-----------------------"
      - "&7Online: &6%ONLINE%"
      - "&7Rank: &6%RANK%"
      - ""
      - "&7Queue: &6%QUEUE%"
      - "&7Position: &6%POSITION%&7/&9%QUEUESIZE%"
      - ""
      - "&e&oplay.yourserver.com"
      - "&7&m-----------------------"
    hub:
      - "&7&m-----------------------"
      - "&7Online: &6%ONLINE%"
      - "&7Rank: &6%RANK%"
      - ""
      - "&b&oplay.yourserver.com"
      - "&7&m-----------------------"

settings:
  inventory:
    name: "&6Settings GUI"
    size: 9
  scoreboard:
    material: "PAINTING"
    name: "&6Scoreboard"
    slot: 0
    lore-true:
      - "&7&m--------------------------"
      - "&cClick to disable your scoreboard"
      - "&7&m--------------------------"
    lore-false:
      - "&7&m---------------------------"
      - "&aClikc to enable your scoreboard"
      - "&7&m---------------------------"
  chat:
    material: "PAPER"
    name: "&6Chat"
    slot: 1
    lore-true:
      - "&7&m--------------------------"
      - "&cClick to disable your chat"
      - "&7&m--------------------------"
    lore-false:
      - "&7&m---------------------------"
      - "&aClick to enable your chat"
      - "&7&m---------------------------"
  tablist:
    material: "ITEM_FRAME"
    name: "&6Tablist"
    slot: 2
    lore-true:
      - "&7&m--------------------------"
      - "&cClick to disable your tablist"
      - "&7&m--------------------------"
    lore-false:
      - "&7&m---------------------------"
      - "&aClick to enable your tablist"
      - "&7&m---------------------------"

cosmetics:
  name-color:
    display-name: "&7* &6Colored Names"
    lore:
      - ""
      - "&7Change the color of your name."
      - ""
    slot: 0
  double-jump:
    display-name: "&7* &6Double-Jump"
    lore:
      - ""
      - "&7Double jump away!"
      - ""
items-inventory:
  name: "&6Items"
  size: 36

server-gui:
  name: "&6Servers"
  size: 9
cosmetic-inventory:
  name: "&6Cosmetics"
  size: 9

border: #this is an example border where it limits the map to 500x500. Players can move 500 in every direction but if they go pass 500 it will tp them back to spawn
  x: 500
  y: 500

servers:
  YourServer:
    material: "DIAMOND_SWORD"
    name: "&7* &6&lYour-Server"
    lore:
      - "&7&m----------------------"
      - "&7Online: &6%ONLINE%" #Simple Placeholder
      - "&7Queue: &6%QUEUESIZE%"
      - "&7&m----------------------"
    command: "queue YourServer"
    slot: 0 #Slot placement in the server gui
    ip: "localhost" #Make sure this information is right. This will ping the server and get the player count
    port: 25567
  YouServer2:
    material: "DIAMOND_SWORD"
    name: "&7* &6&lYour-Server"
    lore:
      - "&7&m----------------------"
      - "&eSimple Lore"
      - "&7&m----------------------"
    command: "queue YourServer2" #This must match whatever you put for queue name
    slot: 0 #Slot placement in the server gui
    ip: "localhost" #Make sure this information is right. This will ping the server and get teh player count
    port: 25567

queues:
  YourServer:
    name: "YourServer" #THIS HAS TO MATCH WHATEVER YOU PUT FOR SERVERS OR SERVER SELECTOR WILL NOT WORK
    maxplayers: 120
    paused: false #If this is true, the queue will stop sending players to the server and thus it will pause.
  YourServer2:
    name: "YourServer2" #This must match whatever you put for command in the servers section of the config.
    maxplayers: 120
    paused: false
ranks:
  Rank2: #It is recommended that this matches the name below.
    name: "Rank2" #This is simply the name of the rank. It is recommended that this matches the name above.
    prefix: "&7[&4Rank2&7]" #Prefix used in chat.
    ladder: 2 # This is the queue priority, the higher the better.
    permissions: #These are the permissions.
      - "this.is.a.permission"
  Rank1: #It is recommended that this matches the name below.
    name: "Rank1" #This is simply the name of the rank. It is recommended that this matches the name above.
    prefix: "&7[&cRank1&7]" #Prefix used in chat.
    ladder: 1 # This is the queue priority, the higher the better.
    permissions: #These are the permissions.
      - "this.is.a.permission"
  Default: #It is recommended that this matches the name below.
    name: "Default" #This is simply the name of the rank. It is recommended that this matches the name above.
    prefix: "&7[&fDefault&7]" #Prefix used in chat.
    ladder: 0 # This is the queue priority, the higher the better.
    permissions: #These are the permissions.
      - "this.is.a.permission"